#Settings for the MODBUS Connection
method: tcp

#MODBUS TCP
ip: '192.168.0.20'
tcpPort: 502

#MODBUS RTU
rtuPort: /dev/ttyUSB0
stopbits: 1
bytesize: 8
parity: N
baudrate: 9600
timeout: 1

#Logging
logging: enable