#Settings for the graphical ploting tools
plot_cfg:
    y_axis_min: 0
    y_axis_max: 100
    x_axis_length: 50
    y_axis_label: 'PV'
    x_axis_label: 'Time'

pen_1:
    name: "PV"
    colour: "go-"
    plot: 1

pen_2:
    name: "SP"
    colour: "b^-"
    plot: 1

#pen_3:
#    name: "OP"
#    colour: "rx-"
#    plot: 2